export const CONTROL_SEED = [

  // ── Group 1: Governance & Accountability (10 controls) ──────────
  {
    control_id: 'CTL-GOV-001',
    name: 'Governance Committee Establishment',
    objective: 'จัดตั้งคณะกรรมการกำกับดูแลด้าน IT/Data/PDPA ขององค์กร',
    description: 'องค์กรต้องมีคณะกรรมการหรือโครงสร้างกำกับดูแลที่ชัดเจน มีการกำหนดอำนาจหน้าที่ และประชุมอย่างสม่ำเสมอ',
    type: 'governance', frequency: 'periodic', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Terms of Reference, Meeting Minutes',
  },
  {
    control_id: 'CTL-GOV-002',
    name: 'IT/Data Policy Approval Process',
    objective: 'กำหนดกระบวนการอนุมัตินโยบายด้าน IT และ Data',
    description: 'นโยบายสำคัญทุกฉบับต้องผ่านกระบวนการ review และ approve โดยผู้บริหารระดับที่เหมาะสม',
    type: 'governance', frequency: 'event_driven', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Policy document with approval signature',
  },
  {
    control_id: 'CTL-GOV-003',
    name: 'Role and Responsibility Assignment',
    objective: 'กำหนด owner, custodian และ user สำหรับ IT assets และข้อมูลสำคัญ',
    description: 'ทุก IT asset และข้อมูลสำคัญต้องมีผู้รับผิดชอบที่ชัดเจน',
    type: 'administrative', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'RACI matrix, Asset ownership register',
  },
  {
    control_id: 'CTL-GOV-004',
    name: 'Governance Performance Monitoring',
    objective: 'ติดตามและรายงานสถานะ governance ต่อผู้บริหาร',
    description: 'มีการจัดทำ governance dashboard และรายงานผลการดำเนินงาน governance ต่อ board/management อย่างสม่ำเสมอ',
    type: 'governance', frequency: 'periodic', criticality: 'medium', related_domain_code: 'IT_GOV',
    expected_evidence: 'Governance reports, Dashboard screenshots',
  },
  {
    control_id: 'CTL-GOV-005',
    name: 'Compliance Obligation Tracking',
    objective: 'ติดตามข้อกำหนดกฎหมายและมาตรฐานที่เกี่ยวข้อง',
    description: 'องค์กรต้องมีระบบติดตามการเปลี่ยนแปลงของกฎหมาย กฎระเบียบ และมาตรฐานที่เกี่ยวข้อง',
    type: 'governance', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Regulatory change log, Compliance calendar',
  },
  {
    control_id: 'CTL-GOV-006',
    name: 'Internal Audit Program',
    objective: 'ดำเนินการตรวจสอบภายในด้าน IT/Data/PDPA',
    description: 'มีแผนและดำเนินการ internal audit ด้าน governance อย่างสม่ำเสมอ',
    type: 'detective', frequency: 'periodic', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Audit plan, Audit report, Finding log',
  },
  {
    control_id: 'CTL-GOV-007',
    name: 'Exception and Deviation Management',
    objective: 'บริหารจัดการกรณีที่ไม่สามารถปฏิบัติตามนโยบายได้',
    description: 'มีกระบวนการขอยกเว้นนโยบาย (policy exception) พร้อมการอนุมัติและติดตาม',
    type: 'governance', frequency: 'event_driven', criticality: 'medium', related_domain_code: 'IT_GOV',
    expected_evidence: 'Exception request form, Approval record',
  },
  {
    control_id: 'CTL-GOV-008',
    name: 'Governance Training and Awareness',
    objective: 'ให้ความรู้ด้าน governance แก่บุคลากร',
    description: 'มีโครงการฝึกอบรมและสร้างความตระหนักด้าน IT governance, PDPA และ data privacy',
    type: 'administrative', frequency: 'periodic', criticality: 'medium', related_domain_code: 'IT_GOV',
    expected_evidence: 'Training records, Attendance list, Assessment result',
  },
  {
    control_id: 'CTL-GOV-009',
    name: 'DPO Appointment and Function',
    objective: 'แต่งตั้งและสนับสนุนการทำงานของ DPO',
    description: 'องค์กรต้องแต่งตั้ง DPO ที่มีความรู้ความสามารถเพียงพอ และให้ทรัพยากรที่จำเป็น',
    type: 'governance', frequency: 'ongoing', criticality: 'high', related_domain_code: 'PDPA',
    expected_evidence: 'DPO appointment letter, Job description',
  },
  {
    control_id: 'CTL-GOV-010',
    name: 'Third Party Governance Framework',
    objective: 'กำหนดกรอบการกำกับดูแลบุคคลภายนอก',
    description: 'มีนโยบายและกระบวนการกำกับดูแล vendor/partner ที่เกี่ยวข้องกับข้อมูลและ IT',
    type: 'governance', frequency: 'ongoing', criticality: 'high', related_domain_code: 'THIRD_PARTY',
    expected_evidence: 'Third party policy, Vendor register',
  },

  // ── Group 2: Risk Management (10 controls) ──────────────────────
  {
    control_id: 'CTL-RSK-001',
    name: 'IT Risk Assessment Process',
    objective: 'ดำเนินการประเมินความเสี่ยงด้าน IT อย่างสม่ำเสมอ',
    description: 'มีกระบวนการประเมินความเสี่ยงด้าน IT ที่ครอบคลุม likelihood, impact และ existing controls',
    type: 'process', frequency: 'periodic', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Risk assessment report, Risk register',
  },
  {
    control_id: 'CTL-RSK-002',
    name: 'Risk Appetite and Tolerance Definition',
    objective: 'กำหนด risk appetite และ tolerance ขององค์กร',
    description: 'ผู้บริหารต้องกำหนดระดับความเสี่ยงที่ยอมรับได้และสื่อสารให้ทุกระดับเข้าใจ',
    type: 'governance', frequency: 'periodic', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Risk appetite statement, Board approval',
  },
  {
    control_id: 'CTL-RSK-003',
    name: 'Risk Treatment Plan',
    objective: 'จัดทำและติดตาม risk treatment plan',
    description: 'ทุก risk ที่สำคัญต้องมี treatment plan ที่ชัดเจน พร้อม owner และ due date',
    type: 'process', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Risk treatment plan, Action status report',
  },
  {
    control_id: 'CTL-RSK-004',
    name: 'Risk Monitoring and Reporting',
    objective: 'ติดตามและรายงาน risk status ต่อผู้บริหาร',
    description: 'มีการรายงาน top risks และการเปลี่ยนแปลง risk profile ต่อ management อย่างสม่ำเสมอ',
    type: 'detective', frequency: 'periodic', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Risk dashboard, Management report',
  },
  {
    control_id: 'CTL-RSK-005',
    name: 'DPIA / Privacy Impact Assessment',
    objective: 'ประเมินผลกระทบด้านความเป็นส่วนตัวก่อนดำเนินโครงการสำคัญ',
    description: 'โครงการที่มีความเสี่ยงสูงต่อข้อมูลส่วนบุคคลต้องผ่านการทำ DPIA ก่อนดำเนินการ',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'PDPA',
    expected_evidence: 'DPIA report, Approval record',
  },
  {
    control_id: 'CTL-RSK-006',
    name: 'AI Risk Assessment',
    objective: 'ประเมินความเสี่ยงของการใช้งาน AI',
    description: 'ก่อนนำ AI มาใช้งานในองค์กรต้องมีการประเมินความเสี่ยงด้านข้อมูล ความโปร่งใส และ bias',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'AI',
    expected_evidence: 'AI risk assessment report',
  },
  {
    control_id: 'CTL-RSK-007',
    name: 'Vendor Risk Assessment',
    objective: 'ประเมินความเสี่ยงของ vendor/third party',
    description: 'Vendor ที่เข้าถึงข้อมูลสำคัญหรือระบบหลักต้องผ่านการประเมินความเสี่ยงก่อนทำสัญญา',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'THIRD_PARTY',
    expected_evidence: 'Vendor assessment report, Due diligence checklist',
  },
  {
    control_id: 'CTL-RSK-008',
    name: 'Business Continuity Risk Assessment',
    objective: 'ประเมินความเสี่ยงต่อความต่อเนื่องทางธุรกิจ',
    description: 'มีการประเมินความเสี่ยงและจัดทำ BCP/DRP สำหรับระบบสำคัญ',
    type: 'process', frequency: 'periodic', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'BCP/DRP document, BIA report',
  },
  {
    control_id: 'CTL-RSK-009',
    name: 'Emerging Risk Identification',
    objective: 'ระบุความเสี่ยงใหม่ที่เกิดขึ้นจากเทคโนโลยีหรือสภาพแวดล้อม',
    description: 'มีกระบวนการติดตามและระบุ emerging risks เช่น AI risks, cloud risks, supply chain risks',
    type: 'detective', frequency: 'periodic', criticality: 'medium', related_domain_code: 'IT_RISK',
    expected_evidence: 'Emerging risk log, Horizon scanning report',
  },
  {
    control_id: 'CTL-RSK-010',
    name: 'Control Effectiveness Testing',
    objective: 'ทดสอบประสิทธิภาพของ controls ที่มีอยู่',
    description: 'มีการทดสอบว่า controls ทำงานได้จริงและมีประสิทธิภาพตามที่ออกแบบไว้',
    type: 'detective', frequency: 'periodic', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Control testing report, Test evidence',
  },

  // ── Group 3: Data Protection / PDPA (10 controls) ───────────────
  {
    control_id: 'CTL-DAT-001',
    name: 'ROPA (Records of Processing Activities)',
    objective: 'จัดทำและบำรุงรักษาบันทึกการประมวลผลข้อมูลส่วนบุคคล',
    description: 'องค์กรต้องมี ROPA ที่ครบถ้วน ทันสมัย และสะท้อนกิจกรรมการประมวลผลจริง',
    type: 'process', frequency: 'ongoing', criticality: 'critical', related_domain_code: 'PDPA',
    expected_evidence: 'ROPA register, Last review date',
  },
  {
    control_id: 'CTL-DAT-002',
    name: 'Data Classification Policy',
    objective: 'กำหนดนโยบายและกระบวนการจำแนกประเภทข้อมูล',
    description: 'ข้อมูลต้องได้รับการจำแนกประเภท (Public, Internal, Confidential, Restricted) และจัดการตามระดับความลับ',
    type: 'policy', frequency: 'ongoing', criticality: 'high', related_domain_code: 'DATA',
    expected_evidence: 'Data classification policy, Asset classification register',
  },
  {
    control_id: 'CTL-DAT-003',
    name: 'Consent Management',
    objective: 'บริหารจัดการการขอและจัดเก็บความยินยอม',
    description: 'มีระบบและกระบวนการขอ จัดเก็บ และถอนความยินยอมที่สอดคล้องกับ PDPA',
    type: 'process', frequency: 'ongoing', criticality: 'critical', related_domain_code: 'PDPA',
    expected_evidence: 'Consent management system, Consent records',
  },
  {
    control_id: 'CTL-DAT-004',
    name: 'Data Retention and Disposal Policy',
    objective: 'กำหนดนโยบายการเก็บรักษาและทำลายข้อมูล',
    description: 'ข้อมูลต้องมีกำหนดอายุการเก็บรักษาที่ชัดเจนและต้องถูกทำลายอย่างปลอดภัยเมื่อหมดอายุ',
    type: 'policy', frequency: 'ongoing', criticality: 'high', related_domain_code: 'PDPA',
    expected_evidence: 'Retention schedule, Disposal records',
  },
  {
    control_id: 'CTL-DAT-005',
    name: 'Privacy Notice Management',
    objective: 'จัดทำและบำรุงรักษาประกาศความเป็นส่วนตัว',
    description: 'มี Privacy Notice/Policy ที่ครบถ้วน เป็นปัจจุบัน และเผยแพร่ให้เจ้าของข้อมูลทราบ',
    type: 'process', frequency: 'ongoing', criticality: 'high', related_domain_code: 'PDPA',
    expected_evidence: 'Privacy notice, Publication evidence',
  },
  {
    control_id: 'CTL-DAT-006',
    name: 'Data Subject Rights Management',
    objective: 'บริหารจัดการคำขอใช้สิทธิของเจ้าของข้อมูล',
    description: 'มีกระบวนการรับและดำเนินการคำขอใช้สิทธิ DSAR (เข้าถึง แก้ไข ลบ คัดค้าน ฯลฯ) ภายใน SLA',
    type: 'process', frequency: 'ongoing', criticality: 'critical', related_domain_code: 'PDPA',
    expected_evidence: 'DSAR log, SLA compliance report',
  },
  {
    control_id: 'CTL-DAT-007',
    name: 'Data Minimization and Purpose Limitation',
    objective: 'รวบรวมและใช้ข้อมูลเท่าที่จำเป็นตามวัตถุประสงค์',
    description: 'กระบวนการเก็บรวบรวมข้อมูลต้องจำกัดเฉพาะข้อมูลที่จำเป็น และใช้ตามวัตถุประสงค์ที่แจ้งไว้',
    type: 'process', frequency: 'ongoing', criticality: 'high', related_domain_code: 'PDPA',
    expected_evidence: 'Data flow diagram, Purpose documentation',
  },
  {
    control_id: 'CTL-DAT-008',
    name: 'Cross-border Data Transfer Control',
    objective: 'ควบคุมการส่งข้อมูลส่วนบุคคลออกนอกประเทศ',
    description: 'การส่งข้อมูลส่วนบุคคลไปยังต่างประเทศต้องเป็นไปตามหลักเกณฑ์ที่ PDPA กำหนด',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'PDPA',
    expected_evidence: 'Transfer mechanism documentation, Adequacy assessment',
  },
  {
    control_id: 'CTL-DAT-009',
    name: 'Data Processor Agreement (DPA)',
    objective: 'จัดทำสัญญากับผู้ประมวลผลข้อมูล',
    description: 'Vendor/third party ที่ประมวลผลข้อมูลส่วนบุคคลแทนองค์กรต้องมีสัญญา DPA ที่ครบถ้วน',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'PDPA',
    expected_evidence: 'Signed DPA agreements',
  },
  {
    control_id: 'CTL-DAT-010',
    name: 'Data Quality Management',
    objective: 'รักษาคุณภาพและความถูกต้องของข้อมูล',
    description: 'มีกระบวนการตรวจสอบและรักษาคุณภาพข้อมูล รวมถึงกระบวนการแก้ไขข้อมูลที่ไม่ถูกต้อง',
    type: 'process', frequency: 'ongoing', criticality: 'medium', related_domain_code: 'DATA',
    expected_evidence: 'Data quality report, Correction log',
  },

  // ── Group 4: Access Control (8 controls) ────────────────────────
  {
    control_id: 'CTL-ACC-001',
    name: 'User Access Management Policy',
    objective: 'กำหนดนโยบายการบริหารจัดการสิทธิ์การเข้าถึง',
    description: 'มีนโยบายที่ครอบคลุม user provisioning, de-provisioning, privilege management และ least privilege',
    type: 'policy', frequency: 'ongoing', criticality: 'critical', related_domain_code: 'IT_GOV',
    expected_evidence: 'Access management policy',
  },
  {
    control_id: 'CTL-ACC-002',
    name: 'Privileged Access Control',
    objective: 'ควบคุมการเข้าถึงของ privileged accounts',
    description: 'Privileged accounts ต้องได้รับการอนุมัติ ควบคุม และ monitor เป็นพิเศษ',
    type: 'technical', frequency: 'ongoing', criticality: 'critical', related_domain_code: 'IT_RISK',
    expected_evidence: 'PAM logs, Privileged account inventory',
  },
  {
    control_id: 'CTL-ACC-003',
    name: 'Periodic Access Review',
    objective: 'ทบทวนสิทธิ์การเข้าถึงอย่างสม่ำเสมอ',
    description: 'มีการทบทวนสิทธิ์การเข้าถึงระบบและข้อมูลสำคัญอย่างน้อยปีละครั้งหรือเมื่อมีการเปลี่ยนแปลงตำแหน่ง',
    type: 'detective', frequency: 'periodic', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Access review report, Sign-off records',
  },
  {
    control_id: 'CTL-ACC-004',
    name: 'Multi-Factor Authentication (MFA)',
    objective: 'ใช้งาน MFA สำหรับระบบสำคัญ',
    description: 'ระบบที่มีข้อมูลสำคัญหรือ privileged access ต้องกำหนดให้ใช้ MFA',
    type: 'technical', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'MFA configuration, Coverage report',
  },
  {
    control_id: 'CTL-ACC-005',
    name: 'Remote Access Control',
    objective: 'ควบคุมการเข้าถึงระบบจากระยะไกล',
    description: 'การ remote access ต้องผ่าน secure channel (VPN/Zero Trust) และมีการ authenticate ที่เข้มแข็ง',
    type: 'technical', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Remote access policy, VPN logs',
  },
  {
    control_id: 'CTL-ACC-006',
    name: 'Service Account Management',
    objective: 'บริหารจัดการ service accounts และ API keys',
    description: 'Service accounts ต้องมีการบริหารจัดการ lifecycle ที่ชัดเจน ไม่ใช้ shared credentials',
    type: 'technical', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Service account inventory, Rotation records',
  },
  {
    control_id: 'CTL-ACC-007',
    name: 'Segregation of Duties',
    objective: 'แบ่งแยกหน้าที่เพื่อป้องกันการฉ้อโกง',
    description: 'งานที่มีความเสี่ยงสูงต้องมีการแบ่งแยกหน้าที่ ไม่ให้คนเดียวสามารถดำเนินงานตั้งแต่ต้นถึงปลายได้',
    type: 'administrative', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'SoD matrix, Access matrix',
  },
  {
    control_id: 'CTL-ACC-008',
    name: 'Identity and Access Governance',
    objective: 'บริหารจัดการ identity lifecycle อย่างเป็นระบบ',
    description: 'มีกระบวนการ onboarding/offboarding ที่ครบถ้วน รวมถึงการเพิกถอนสิทธิ์เมื่อพ้นสภาพพนักงาน',
    type: 'process', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'IAM procedure, Offboarding checklist',
  },

  // ── Group 5: Third Party (7 controls) ───────────────────────────
  {
    control_id: 'CTL-3RD-001',
    name: 'Third Party Due Diligence',
    objective: 'ตรวจสอบความน่าเชื่อถือของ vendor/partner ก่อนทำสัญญา',
    description: 'มีกระบวนการ due diligence ด้าน security, privacy และ compliance สำหรับ vendor ที่เกี่ยวข้องกับข้อมูลสำคัญ',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'THIRD_PARTY',
    expected_evidence: 'Due diligence report, Questionnaire responses',
  },
  {
    control_id: 'CTL-3RD-002',
    name: 'Vendor Contract Security Requirements',
    objective: 'กำหนดข้อกำหนดด้านความปลอดภัยในสัญญา',
    description: 'สัญญากับ vendor ที่เข้าถึงข้อมูลหรือระบบสำคัญต้องมีข้อกำหนดด้าน security และ privacy ที่เพียงพอ',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'THIRD_PARTY',
    expected_evidence: 'Contract with security clauses, DPA agreement',
  },
  {
    control_id: 'CTL-3RD-003',
    name: 'Ongoing Vendor Performance Monitoring',
    objective: 'ติดตามการปฏิบัติตามสัญญาของ vendor',
    description: 'มีการ monitor การปฏิบัติตาม SLA, security requirements และ compliance ของ vendor อย่างต่อเนื่อง',
    type: 'detective', frequency: 'periodic', criticality: 'medium', related_domain_code: 'THIRD_PARTY',
    expected_evidence: 'Vendor review report, KPI monitoring',
  },
  {
    control_id: 'CTL-3RD-004',
    name: 'Cloud Service Provider Assessment',
    objective: 'ประเมินความเสี่ยงของการใช้ Cloud Services',
    description: 'ก่อนใช้งาน cloud service ต้องมีการประเมินความปลอดภัยและ compliance ของ provider',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Cloud assessment report, Shared responsibility matrix',
  },
  {
    control_id: 'CTL-3RD-005',
    name: 'Outsourcing Risk Management',
    objective: 'บริหารความเสี่ยงของงานที่ outsource',
    description: 'มีการระบุและบริหารความเสี่ยงที่เกิดจากการ outsource งาน IT และ data processing',
    type: 'process', frequency: 'ongoing', criticality: 'high', related_domain_code: 'THIRD_PARTY',
    expected_evidence: 'Outsourcing risk register, Mitigation plan',
  },
  {
    control_id: 'CTL-3RD-006',
    name: 'Supply Chain Security',
    objective: 'บริหารความเสี่ยงด้านความปลอดภัยของ supply chain',
    description: 'มีการประเมินและควบคุมความเสี่ยงจาก software/hardware supply chain',
    type: 'process', frequency: 'periodic', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Supply chain risk assessment, SBOM',
  },
  {
    control_id: 'CTL-3RD-007',
    name: 'Vendor Offboarding Process',
    objective: 'กระบวนการยุติความสัมพันธ์กับ vendor อย่างปลอดภัย',
    description: 'เมื่อสิ้นสุดสัญญากับ vendor ต้องมีกระบวนการเพิกถอนสิทธิ์และนำข้อมูลกลับคืนอย่างปลอดภัย',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'THIRD_PARTY',
    expected_evidence: 'Offboarding checklist, Data return/destruction evidence',
  },

  // ── Group 6: Incident & Breach (8 controls) ─────────────────────
  {
    control_id: 'CTL-INC-001',
    name: 'Security Incident Response Plan',
    objective: 'มีแผนตอบสนองต่อเหตุการณ์ความปลอดภัย',
    description: 'มี Incident Response Plan ที่ครอบคลุม detection, containment, eradication, recovery และ lessons learned',
    type: 'process', frequency: 'ongoing', criticality: 'critical', related_domain_code: 'IT_RISK',
    expected_evidence: 'IRP document, Drill exercise record',
  },
  {
    control_id: 'CTL-INC-002',
    name: 'Personal Data Breach Notification',
    objective: 'แจ้ง PDPC และเจ้าของข้อมูลเมื่อเกิด data breach',
    description: 'เมื่อเกิด personal data breach ต้องแจ้ง PDPC ภายใน 72 ชั่วโมง และแจ้งเจ้าของข้อมูลตามที่กำหนด',
    type: 'process', frequency: 'event_driven', criticality: 'critical', related_domain_code: 'PDPA',
    expected_evidence: 'Breach log, Notification records, PDPC report',
  },
  {
    control_id: 'CTL-INC-003',
    name: 'Incident Classification and Severity',
    objective: 'จำแนกประเภทและระดับความรุนแรงของเหตุการณ์',
    description: 'มีกรอบการจำแนกประเภท incident และระดับความรุนแรงที่ชัดเจน เพื่อให้ตอบสนองได้อย่างเหมาะสม',
    type: 'process', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Incident classification matrix',
  },
  {
    control_id: 'CTL-INC-004',
    name: 'Incident Log and Tracking',
    objective: 'บันทึกและติดตาม security incidents ทั้งหมด',
    description: 'มีระบบบันทึก incidents ที่ครบถ้วน รวมถึง root cause, impact และ remediation actions',
    type: 'detective', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Incident log/ticketing system',
  },
  {
    control_id: 'CTL-INC-005',
    name: 'Post-Incident Review',
    objective: 'ทบทวนบทเรียนหลังเหตุการณ์สำคัญ',
    description: 'หลัง incident สำคัญต้องมีการทบทวนบทเรียน (lessons learned) และปรับปรุงมาตรการ',
    type: 'process', frequency: 'event_driven', criticality: 'medium', related_domain_code: 'IT_RISK',
    expected_evidence: 'Post-incident review report',
  },
  {
    control_id: 'CTL-INC-006',
    name: 'Security Monitoring and Alerting',
    objective: 'ตรวจจับและแจ้งเตือนเหตุการณ์ผิดปกติ',
    description: 'มีระบบ monitoring ที่ครอบคลุมระบบสำคัญ พร้อม alerting เมื่อตรวจพบความผิดปกติ',
    type: 'detective', frequency: 'ongoing', criticality: 'high', related_domain_code: 'CYBER',
    expected_evidence: 'SIEM/monitoring tool, Alert rules',
  },
  {
    control_id: 'CTL-INC-007',
    name: 'Vulnerability Management',
    objective: 'บริหารจัดการช่องโหว่ด้านความปลอดภัย',
    description: 'มีกระบวนการ scan, ประเมิน และแก้ไขช่องโหว่อย่างสม่ำเสมอตาม SLA ที่กำหนด',
    type: 'preventive', frequency: 'periodic', criticality: 'high', related_domain_code: 'CYBER',
    expected_evidence: 'Vulnerability scan report, Patch records',
  },
  {
    control_id: 'CTL-INC-008',
    name: 'Forensic and Evidence Preservation',
    objective: 'เก็บรักษาหลักฐานดิจิทัลอย่างถูกต้อง',
    description: 'มีกระบวนการเก็บรักษาหลักฐานดิจิทัลที่เกี่ยวกับ incident เพื่อใช้ในการสืบสวนและดำเนินคดี',
    type: 'process', frequency: 'event_driven', criticality: 'medium', related_domain_code: 'IT_RISK',
    expected_evidence: 'Evidence preservation procedure, Chain of custody',
  },

  // ── Group 7: Change & Project Governance (8 controls) ───────────
  {
    control_id: 'CTL-CHG-001',
    name: 'Change Management Process',
    objective: 'บริหารจัดการการเปลี่ยนแปลง IT อย่างเป็นระบบ',
    description: 'การเปลี่ยนแปลงระบบ IT ต้องผ่านกระบวนการ request, review, approve และ test ก่อน deploy',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Change request records, CAB minutes',
  },
  {
    control_id: 'CTL-CHG-002',
    name: 'Emergency Change Process',
    objective: 'บริหารจัดการการเปลี่ยนแปลงฉุกเฉิน',
    description: 'มีกระบวนการพิเศษสำหรับ emergency change ที่รวดเร็วแต่ยังคงความรับผิดชอบ',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Emergency change log, Post-change review',
  },
  {
    control_id: 'CTL-CHG-003',
    name: 'Software Development Security (SDLC)',
    objective: 'รวม security เข้าในกระบวนการพัฒนาซอฟต์แวร์',
    description: 'กระบวนการพัฒนาซอฟต์แวร์ต้องรวม security review, code scan และ security testing',
    type: 'process', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'SDLC security checklist, Scan reports',
  },
  {
    control_id: 'CTL-CHG-004',
    name: 'IT Project Risk Management',
    objective: 'บริหารความเสี่ยงในโครงการ IT',
    description: 'โครงการ IT สำคัญต้องมีการระบุและบริหารความเสี่ยงตลอดช่วงโครงการ',
    type: 'process', frequency: 'ongoing', criticality: 'medium', related_domain_code: 'IT_GOV',
    expected_evidence: 'Project risk register, Steering committee minutes',
  },
  {
    control_id: 'CTL-CHG-005',
    name: 'Release and Deployment Management',
    objective: 'บริหารจัดการการ release และ deploy ระบบ',
    description: 'มีกระบวนการ release management ที่ครอบคลุม testing, staging และ rollback plan',
    type: 'process', frequency: 'event_driven', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Release plan, Test results, Rollback procedure',
  },
  {
    control_id: 'CTL-CHG-006',
    name: 'Configuration Management',
    objective: 'บริหารจัดการ configuration ของระบบ IT',
    description: 'มี CMDB และกระบวนการควบคุม configuration ที่ป้องกันการเปลี่ยนแปลงโดยไม่ได้รับอนุญาต',
    type: 'technical', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'CMDB, Configuration baseline',
  },
  {
    control_id: 'CTL-CHG-007',
    name: 'Architecture Review Board',
    objective: 'ทบทวนสถาปัตยกรรมระบบก่อนดำเนินโครงการ',
    description: 'โครงการที่มีผลกระทบต่อ architecture สำคัญต้องผ่านการ review จาก Architecture Review Board',
    type: 'governance', frequency: 'event_driven', criticality: 'medium', related_domain_code: 'IT_GOV',
    expected_evidence: 'ARB approval, Architecture decision record',
  },
  {
    control_id: 'CTL-CHG-008',
    name: 'Patch Management',
    objective: 'บริหารจัดการการ patch ระบบ IT',
    description: 'มีกระบวนการ patch management ที่ครอบคลุม critical patches และตรงตาม SLA ที่กำหนด',
    type: 'preventive', frequency: 'periodic', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Patch management report, Compliance metrics',
  },

  // ── Group 8: AI Governance (6 controls) ─────────────────────────
  {
    control_id: 'CTL-AI-001',
    name: 'AI Use Case Approval',
    objective: 'ขออนุมัติก่อนนำ AI มาใช้งานในองค์กร',
    description: 'การนำ AI มาใช้งานในกระบวนการสำคัญต้องผ่านการ review และอนุมัติจากคณะกรรมการที่กำหนด',
    type: 'governance', frequency: 'event_driven', criticality: 'high', related_domain_code: 'AI',
    expected_evidence: 'AI use case register, Approval records',
  },
  {
    control_id: 'CTL-AI-002',
    name: 'Human Oversight of AI Decisions',
    objective: 'กำหนดให้มีการตรวจสอบโดยมนุษย์สำหรับการตัดสินใจ AI ที่สำคัญ',
    description: 'การตัดสินใจที่มีผลกระทบสูงที่ใช้ AI ต้องมีกลไก human oversight ที่เพียงพอ',
    type: 'governance', frequency: 'ongoing', criticality: 'high', related_domain_code: 'AI',
    expected_evidence: 'Human review logs, Override records',
  },
  {
    control_id: 'CTL-AI-003',
    name: 'AI Model Transparency and Explainability',
    objective: 'รับรองความโปร่งใสของ AI model',
    description: 'AI ที่ใช้กับลูกค้าหรือการตัดสินใจสำคัญต้องมีความสามารถในการอธิบายผลลัพธ์',
    type: 'technical', frequency: 'ongoing', criticality: 'medium', related_domain_code: 'AI',
    expected_evidence: 'Model documentation, Explainability report',
  },
  {
    control_id: 'CTL-AI-004',
    name: 'AI Bias and Fairness Assessment',
    objective: 'ประเมินและลด bias ใน AI model',
    description: 'AI model ที่ใช้กับมนุษย์ต้องผ่านการประเมิน bias และมีมาตรการลดความเลือกปฏิบัติ',
    type: 'process', frequency: 'periodic', criticality: 'high', related_domain_code: 'AI',
    expected_evidence: 'Bias assessment report, Fairness metrics',
  },
  {
    control_id: 'CTL-AI-005',
    name: 'AI Data Privacy Compliance',
    objective: 'รับรองว่า AI ประมวลผลข้อมูลสอดคล้องกับ PDPA',
    description: 'การใช้ข้อมูลส่วนบุคคลในการ train หรือใช้งาน AI ต้องสอดคล้องกับหลักการ PDPA',
    type: 'process', frequency: 'ongoing', criticality: 'high', related_domain_code: 'AI',
    expected_evidence: 'Data processing documentation, Legal basis assessment',
  },
  {
    control_id: 'CTL-AI-006',
    name: 'AI Incident and Monitoring',
    objective: 'ติดตามและจัดการปัญหาที่เกิดจาก AI',
    description: 'มีกระบวนการติดตามประสิทธิภาพ AI และจัดการกรณีที่ AI ทำงานผิดพลาดหรือสร้างผลลัพธ์ที่ไม่เหมาะสม',
    type: 'detective', frequency: 'ongoing', criticality: 'high', related_domain_code: 'AI',
    expected_evidence: 'AI monitoring logs, Incident records',
  },

  // ── Group 9: Evidence & Audit (8 controls) ──────────────────────
  {
    control_id: 'CTL-EVD-001',
    name: 'Evidence Collection and Storage',
    objective: 'จัดเก็บหลักฐานการปฏิบัติตาม controls อย่างเป็นระบบ',
    description: 'มีกระบวนการรวบรวม จัดเก็บ และบำรุงรักษาหลักฐานการปฏิบัติตาม controls',
    type: 'process', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Evidence repository, Storage policy',
  },
  {
    control_id: 'CTL-EVD-002',
    name: 'Audit Trail Implementation',
    objective: 'บันทึก audit trail สำหรับการเข้าถึงและเปลี่ยนแปลงข้อมูลสำคัญ',
    description: 'ระบบที่มีข้อมูลสำคัญต้องมีการบันทึก audit trail ที่ครบถ้วน tamper-proof และเก็บรักษาตามที่กำหนด',
    type: 'technical', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Audit log samples, Log retention policy',
  },
  {
    control_id: 'CTL-EVD-003',
    name: 'Evidence Review and Validation',
    objective: 'ตรวจสอบความถูกต้องและความเพียงพอของหลักฐาน',
    description: 'มีกระบวนการ review หลักฐานเพื่อรับรองว่าเพียงพอต่อการ demonstrate compliance',
    type: 'detective', frequency: 'periodic', criticality: 'medium', related_domain_code: 'IT_GOV',
    expected_evidence: 'Evidence review checklist',
  },
  {
    control_id: 'CTL-EVD-004',
    name: 'Evidence Retention Policy',
    objective: 'กำหนดนโยบายการเก็บรักษาหลักฐาน',
    description: 'มีนโยบายกำหนดระยะเวลาการเก็บรักษาหลักฐานตามข้อกำหนดทางกฎหมายและมาตรฐาน',
    type: 'policy', frequency: 'ongoing', criticality: 'medium', related_domain_code: 'IT_GOV',
    expected_evidence: 'Evidence retention schedule',
  },
  {
    control_id: 'CTL-EVD-005',
    name: 'Log Management',
    objective: 'บริหารจัดการ system logs อย่างเหมาะสม',
    description: 'มีการรวบรวม จัดเก็บ และป้องกัน logs จากระบบสำคัญ พร้อมกำหนดอายุการเก็บรักษา',
    type: 'technical', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_RISK',
    expected_evidence: 'Log management policy, SIEM configuration',
  },
  {
    control_id: 'CTL-EVD-006',
    name: 'Compliance Assessment Evidence',
    objective: 'เก็บรักษาหลักฐานผลการประเมิน compliance',
    description: 'ผลการประเมิน controls และ compliance ต้องถูกจัดเก็บพร้อมหลักฐานประกอบ',
    type: 'process', frequency: 'ongoing', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Assessment reports, Evidence attachments',
  },
  {
    control_id: 'CTL-EVD-007',
    name: 'Regulator Examination Readiness',
    objective: 'เตรียมความพร้อมสำหรับการตรวจสอบจากหน่วยงานกำกับดูแล',
    description: 'มีกระบวนการเตรียมเอกสารและหลักฐานสำหรับการตรวจสอบจาก regulator',
    type: 'process', frequency: 'periodic', criticality: 'high', related_domain_code: 'IT_GOV',
    expected_evidence: 'Examination readiness checklist, Evidence package',
  },
  {
    control_id: 'CTL-EVD-008',
    name: 'Continuous Control Monitoring',
    objective: 'ติดตาม control effectiveness อย่างต่อเนื่อง',
    description: 'มีกระบวนการติดตามประสิทธิภาพของ controls อย่างต่อเนื่องผ่านการ monitor metrics และ KRI',
    type: 'detective', frequency: 'ongoing', criticality: 'medium', related_domain_code: 'IT_GOV',
    expected_evidence: 'CCM dashboard, KRI reports',
  },
]
