export const FRAMEWORK_SEED = [
  {
    framework_id: 'PDPA-TH',
    name: 'Thailand PDPA',
    type: 'regulation',
    regulator: 'PDPC Thailand',
    version: '2562',
    effective_date: '2022-06-01',
    description: 'พระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562',
    status: 'active',
    related_domain_code: 'PDPA',
    document_reference: 'https://www.pdpc.or.th',
  },
  {
    framework_id: 'NIST-CSF-2',
    name: 'NIST Cybersecurity Framework 2.0',
    type: 'framework',
    regulator: 'NIST',
    version: '2.0',
    effective_date: '2024-02-26',
    description: 'NIST CSF 2.0 — Govern, Identify, Protect, Detect, Respond, Recover',
    status: 'active',
    related_domain_code: 'CYBER',
    document_reference: 'https://www.nist.gov/cyberframework',
  },
  {
    framework_id: 'NIST-AI-RMF',
    name: 'NIST AI Risk Management Framework',
    type: 'framework',
    regulator: 'NIST',
    version: '1.0',
    effective_date: '2023-01-26',
    description: 'NIST AI RMF — Govern, Map, Measure, Manage AI risks',
    status: 'active',
    related_domain_code: 'AI',
    document_reference: 'https://www.nist.gov/system/files/documents/2023/01/26/NIST.AI.100-1.pdf',
  },
  {
    framework_id: 'ISO-27001',
    name: 'ISO/IEC 27001:2022',
    type: 'standard',
    regulator: 'ISO/IEC',
    version: '2022',
    effective_date: '2022-10-25',
    description: 'Information security management systems — Requirements',
    status: 'active',
    related_domain_code: 'IT_GOV',
    document_reference: 'https://www.iso.org/standard/82875.html',
  },
  {
    framework_id: 'ISO-27701',
    name: 'ISO/IEC 27701:2019',
    type: 'standard',
    regulator: 'ISO/IEC',
    version: '2019',
    effective_date: '2019-08-06',
    description: 'Privacy information management — Extension to ISO/IEC 27001 and 27002',
    status: 'active',
    related_domain_code: 'PDPA',
    document_reference: 'https://www.iso.org/standard/71670.html',
  },
  {
    framework_id: 'COBIT-2019',
    name: 'COBIT 2019',
    type: 'framework',
    regulator: 'ISACA',
    version: '2019',
    effective_date: '2018-11-01',
    description: 'Framework for IT governance and management',
    status: 'active',
    related_domain_code: 'IT_GOV',
    document_reference: 'https://www.isaca.org/resources/cobit',
  },
  {
    framework_id: 'BOT-IT-RISK',
    name: 'BOT IT Risk / AI Risk Guideline',
    type: 'guideline',
    regulator: 'Bank of Thailand',
    version: '2566',
    effective_date: '2023-01-01',
    description: 'แนวทางการบริหารความเสี่ยงด้านเทคโนโลยีสารสนเทศและ AI สำหรับสถาบันการเงิน',
    status: 'active',
    related_domain_code: 'IT_RISK',
    document_reference: 'https://www.bot.or.th',
  },
  {
    framework_id: 'OIC-IT-GOV',
    name: 'OIC IT Governance / IT Risk',
    type: 'guideline',
    regulator: 'Office of Insurance Commission',
    version: '2566',
    effective_date: '2023-01-01',
    description: 'แนวทาง IT Governance และ IT Risk สำหรับธุรกิจประกันภัย',
    status: 'active',
    related_domain_code: 'IT_GOV',
    document_reference: 'https://www.oic.or.th',
  },
  {
    framework_id: 'NCSA-CYBER',
    name: 'NCSA Cybersecurity Baseline',
    type: 'guideline',
    regulator: 'National Cyber Security Agency Thailand',
    version: '1.0',
    effective_date: '2022-01-01',
    description: 'แนวปฏิบัติความมั่นคงปลอดภัยไซเบอร์พื้นฐาน สำหรับหน่วยงานสำคัญ',
    status: 'active',
    related_domain_code: 'CYBER',
    document_reference: 'https://www.ncsa.or.th',
  },
]
